<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260602" />
    <PackageReference Include="OpenCvSharp4.official.runtime.linux-x64" Version="4.13.0.20260602" />
  </ItemGroup>

  <ItemGroup>
    <None Include="OpenCV_Logo.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
